version: '3'
services:
  database:
    image: postgres:16.0
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - database:/var/lib/postgresql/data

  server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - '8080:8080'
    depends_on:
      - database
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@host.docker.internal:5432/postgres
      HASURA_GRAPHQL_CORS_DOMAIN: https://${NEXT_PUBLIC_HASURA_DOMAIN}

  client:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        - NEXT_PUBLIC_VERSION=${NEXT_PUBLIC_VERSION}
        - NEXT_PUBLIC_HASURA_DOMAIN=${NEXT_PUBLIC_HASURA_DOMAIN}
    ports:
      - '3000:3000'
    depends_on:
      - database
      - server

volumes:
  database:
