version: '3'
services:
  database:
    image: postgres:16.0
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - cleanslate:/var/lib/postgresql/data

  graphql-engine:
    image: hasura/graphql-engine:v2.34.0
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - 'database'
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}
      HASURA_GRAPHQL_DATABASE_URL: ${HASURA_GRAPHQL_DATABASE_URL}

volumes:
  cleanslate:
