name: Pull Request

on:
  pull_request:
    branches: [main]

env:
  CI: true
  HASURA_GRAPHQL_ADMIN_SECRET: secret
  HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
  HASURA_GRAPHQL_JWT_SECRET: '{ "type": "HS256", "key": "d374e7c8-912c-4871-bac2-7dde6afc2b55" }'
  NEXT_PUBLIC_CYPRESS: true
  POSTGRES_DB: postgres
  POSTGRES_HOST: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_PORT: 5432
  POSTGRES_USER: postgres

jobs:
  CI:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        volumes:
          - postgres:/var/lib/postgresql/data
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      graphql-engine:
        image: hasura/graphql-engine:v2.36.1
        ports:
          - '8080:8080'
        env:
          HASURA_GRAPHQL_ADMIN_SECRET: secret
          HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
          HASURA_GRAPHQL_JWT_SECRET: '{ "type": "HS256", "key": "d374e7c8-912c-4871-bac2-7dde6afc2b55" }'

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2.4.0
        with:
          version: latest

      - name: Use Node.js
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4
        with:
          node-version: latest
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install Hasura CLI
        run: curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash

      - name: Lint the client
        run: bash -e lint.sh

      - name: Migrate Hasura metadata
        run: node migrate.js

      - name: Configure Cypress
        run: npx cypress install

      - name: Run the Jest and Cypress test suites
        run: pnpm test

      - name: Build the Next.js bundle
        run: cd src && npx next build
